### ISSUE TITLE
[BUG] Crash sometimes

### ISSUE THREAD

**Issue by krisives** [n4n0GH/hello#60]
**Describe the bug**
Plasma crashes. It recovers quickly, but it provides a stack trace.

**To Reproduce**
Unclear. Happens every so often when I hover over decorations within the `applet-window-buttons` widget. Stack trace seems to indicate that while it's happening with that widget the actual crash is within the decoration.

**Expected behavior**
Plasma or KDecration2 shouldn't crash.

**Bug inheritance**
Has never happened with other decorations using the `applet-window-buttons` thingy. 

Backtrace:

```
Thread 1 (Thread 0x7f58548e1e40 (LWP 1448)):
[KCrash Handler]
#6  0x00007f5814d0a957 in KDecoration2::DecorationButton::decoration() const () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#7  0x00007f5814d0a99b in KDecoration2::DecorationButton::update(QRectF const&) () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#8  0x00007f5814d0ac4f in KDecoration2::DecorationButton::update() () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#9  0x00007f584e9279ef in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7ffec07e7cd0, r=0x55b209944fa0, this=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#10 0x00007f584e9279ef in QMetaObject::activate(QObject*, int, int, void**) (sender=0x55b209944fa0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3789
#11 0x00007f584e9279ef in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7ffec07e7e30, r=0x55b20b60e8c0, this=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:394
#12 0x00007f584e9279ef in QMetaObject::activate(QObject*, int, int, void**) (sender=0x55b20b60e8c0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3789
#13 0x00007f5814d0fb02 in KDecoration2::DecorationButton::hoveredChanged(bool) () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#14 0x00007f5814d0b2f2 in KDecoration2::DecorationButton::hoverEnterEvent(QHoverEvent*) () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#15 0x00007f5814d0b616 in KDecoration2::DecorationButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libkdecorations2.so.5
#16 0x00007f5850262eac in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x55b2075bf820, receiver=receiver@entry=0x55b20b60e8c0, e=e@entry=0x7ffec07e8120) at kernel/qapplication.cpp:3703
#17 0x00007f585026a4b0 in QApplication::notify(QObject*, QEvent*) (this=0x7ffec07e9c10, receiver=0x55b20b60e8c0, e=0x7ffec07e8120) at kernel/qapplication.cpp:3449
#18 0x00007f584e8f6f08 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55b20b60e8c0, event=0x7ffec07e8120) at kernel/qcoreapplication.cpp:1095
#19 0x00007f5814f6d1bb in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/appletdecoration/libappletdecorationplugin.so
#20 0x00007f585277cae8 in QQuickItem::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#21 0x00007f5850262eac in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x55b2075bf820, receiver=receiver@entry=0x55b20df04740, e=e@entry=0x7ffec07e84a0) at kernel/qapplication.cpp:3703
#22 0x00007f585026a4b0 in QApplication::notify(QObject*, QEvent*) (this=0x7ffec07e9c10, receiver=0x55b20df04740, e=0x7ffec07e84a0) at kernel/qapplication.cpp:3449
#23 0x00007f584e8f6f08 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55b20df04740, event=0x7ffec07e84a0) at kernel/qcoreapplication.cpp:1095
#24 0x00007f5852793990 in QQuickWindowPrivate::sendHoverEvent(QEvent::Type, QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#25 0x00007f58527947d8 in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#26 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#27 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#28 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#29 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#30 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#31 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#32 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#33 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#34 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#35 0x00007f585279462f in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, unsigned long, bool&) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#36 0x00007f5852798d84 in QQuickWindowPrivate::handleMouseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#37 0x00007f584eed5525 in QWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007f5852799a45 in QQuickWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#39 0x000055b2053696fb in PanelView::event(QEvent*) (this=0x55b209391e70, e=0x7ffec07e9720) at ./shell/panelview.cpp:976
#40 0x00007f5850262eac in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x55b2075bf820, receiver=receiver@entry=0x55b209391e70, e=e@entry=0x7ffec07e9720) at kernel/qapplication.cpp:3703
#41 0x00007f585026a4b0 in QApplication::notify(QObject*, QEvent*) (this=0x7ffec07e9c10, receiver=0x55b209391e70, e=0x7ffec07e9720) at kernel/qapplication.cpp:3449
#42 0x00007f584e8f6f08 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55b209391e70, event=0x7ffec07e9720) at kernel/qcoreapplication.cpp:1095
#43 0x00007f584eeca495 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007f584eecb5e5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#45 0x00007f584eea579b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#46 0x00007f58427afdda in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#47 0x00007f584817b417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007f584817b650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007f584817b6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007f584e954b7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x55b20761da10, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#51 0x00007f584e8f506a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffec07e9ac0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:225
#52 0x00007f584e8fe3e0 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1403
#53 0x000055b205358cef in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ./shell/main.cpp:219
```

**Comment by n4n0GH** [comment]
Seems to be an issue with how the unison hovering is doing it's thing. Can you check if this issue also appears in SierraBreezeEnhanced?

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
